Add SearchBox
slimcandy/todorism pull request #14
Opened 2022-06-29 18:43 UTC by slimcandy

2022-07-08 09:59 UTC, ldudanova commented
считаю, что префикс todo стоит убрать или заменить на иной. Иначе кажется, будто этот цвет нужно переделать. Так же мне кажется, что лучше избегать в наименовании переменной название цвета, в светлой теме основные цвета будут другими, а переменные по факту те же.

2022-07-08 09:59 UTC, ldudanova commented
можем ли мы передавать цвет tailwind'а?

2022-07-11 13:53 UTC, ldudanova requested changes

2022-07-11 13:53 UTC, ldudanova commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          size={20}
Во время ввода текста и когда в поле введен текст иконка должна быть такого же цвета как и во время ховера

2022-07-11 13:53 UTC, ldudanova commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          value={value}
Либо убрать иконку крестика для очистки поля ввода, либо обсудить с дизайнерами её стилизацию.

2022-07-11 13:53 UTC, ldudanova commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          className="input w-full max-w-xs text-current pl-12 h-9 bg-black-2 text-white placeholder:text-dark-2 hover:placeholder:text-dark-3 focus:placeholder:text-white"
Отсутствует состояние disabled

2022-07-11 15:01 UTC, ldudanova commented
Сделать высоту инпута 44px согласно изменениям в макете.

2022-07-12 09:29 UTC, ldudanova commented
Было бы здорово добавить transition для смены цвета

2022-07-17 13:41 UTC, slimcandy commented on src/js/view/components/FindForm/FindForm.tsx
> +            <ZoomIcon size={32} fill="#1C1C28" />
Через классы для стилизации текста

2022-07-21 09:36 UTC, slimcandy commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          value={value}
Исправил по дизайну

2022-07-21 09:37 UTC, slimcandy commented
> Сделать высоту инпута 44px согласно изменениям в макете.

Исправил

2022-07-21 09:37 UTC, slimcandy commented
> Было бы здорово добавить transition для смены цвета

Не увидел это в дизайне

2022-07-21 10:46 UTC, ldudanova commented on src/js/view/components/SearchBar/types.ts
> +export interface SearchBarProps {
Файлы лучше называть по имени их главного элемента, в данном случае interface'а

2022-07-21 10:46 UTC, ldudanova commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          className={`input w-full max-w-xs text-current pl-12 h-11 bg-black-2 text-white placeholder:text-dark-2 hover:placeholder:text-dark-3 focus:placeholder:text-white disabled:text-black-3 disa
Можно сразу добавить стили для светлой темы. Переключение на светлую и темную тему уже доступны в develop.

2022-07-21 11:32 UTC, slimcandy commented on src/js/view/components/SearchBar/types.ts
> +export interface SearchBarProps {
Исправил

2022-07-21 11:33 UTC, slimcandy commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          className={`input w-full max-w-xs text-current pl-12 h-11 bg-black-2 text-white placeholder:text-dark-2 hover:placeholder:text-dark-3 focus:placeholder:text-white disabled:text-black-3 disa
Есть пример?

2022-07-21 11:34 UTC, ldudanova commented on src/js/view/components/SearchBar/types.ts
> +export interface SearchBarProps {
![image](https://user-images.githubusercontent.com/61585545/180204051-09ebb8e1-970d-4de9-b6d4-ec4c827673c8.png)

Запушил?

2022-07-21 12:05 UTC, slimcandy commented on src/js/view/components/SearchBar/SearchBar.tsx
> +          className={`input w-full max-w-xs text-current pl-12 h-11 bg-black-2 text-white placeholder:text-dark-2 hover:placeholder:text-dark-3 focus:placeholder:text-white disabled:text-black-3 disa
В этой ветке такого нет

2022-07-21 12:52 UTC, closed without merging